# Generated by Django 4.1.7 on 2023-05-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_sales_sales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="product_name",
            field=models.CharField(max_length=400),
        ),
    ]
