# Generated by Django 4.1.7 on 2023-05-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_sales_product_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sales",
            old_name="Sales",
            new_name="sales",
        ),
        migrations.AlterField(
            model_name="sales",
            name="subcategory",
            field=models.CharField(max_length=200),
        ),
    ]
